export const FETCH_START = 'FETCH_START';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_LOCAL_SUCCESS = 'FETCH_LOCAL_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';

// export const FETCH_TASKS_START = 'FETCH_TASKS_START';
// export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
// export const FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE';
// export const FETCH_LOCAL_TASKS_SUCCESS = 'FETCH_LOCAL_TASKS_SUCCESS';

export const ADD_BOARD = 'ADD_BOARD';
export const ADD_TASK = 'ADD_TASK';
export const CHANGE_PROGRESS = 'CHANGE_PROGRESS';

export const SELECT_BOARD = 'SELECT_BOARD';